src/config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index' 
  resources :users
  get 'mypage', to: 'users#me'
  get 'user_edit', to: 'users#edit'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  
  # root 'home#index'
  # root 'boards#index'
  # , only: %i[new create edit update show]
  resources :boards do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: %i[create destroy]

  resources :contacts
  post 'contacts/confirm', to: 'contacts#confirm', as: 'contact_confirm'
  post 'contacts/index', to: 'contacts#index', as: 'contact_index'
  post 'contacts/done', to: 'contacts#done', as: 'contact_done'

  get "search" => "searches#search"
end

src/app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text(65535)
#  name       :string(255)
#  title      :string(255)
#  created_at :datetime         not null#
#  updated_at :datetime         not null
#
class Board < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations
  has_one_attached :image
  belongs_to :user , optional: true

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  #投稿が誰にいいねされているのかを簡単に取得

  # validates :name, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_last_month, -> { where(created_at: Time.zone.now.prev_month.all_day) } # １ヶ月前の投稿
  scope :created_month, -> { where(created_at: Time.zone.now.all_month) } # 今月の投稿
end

src/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_target_board, only: %i[show edit update destroy]
  #このアクションのみ

  def index
    #タグ検索
    @q = Board.ransack(params[:q])
    if params[:tag_id].present?
    #タグ検索の処理
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.page(params[:page]).per(8)
    else
    #キーワード検索
    @boards = @q.result(distinct: true).page(params[:page]).per(8)
    .all.order(id: "DESC")
    end

    @boards_count = Board.all.count 
    #掲示板の合計数
    @today_count = Board.created_today.count
    #今日投稿された掲示板の数
    @lastmonth_count = Board.created_last_month.coun
    #先月投稿された掲示板の数
    @month_count = Board.created_month.count 
    #今月投稿された掲示板の数
  end

  def new
    @board = Board.new(flash[:board])
  end

  def create
    @user = current_user
    # board = Board.new(board_params)
    board = @user.boards.build(board_params)
    #userを紐付け
    board.image.attach(params[:board][:image])
    #画像投稿処理
    if board.save
      flash[:notice] = "「#{board.title}」の掲示板を作成しました"
      redirect_to board
    else
      redirect_back fallback_location: root_path, flash: {
        board: board,
        error_messages: board.errors.full_messages
      }
    end
  end

  def show
    @comment = Comment.new(board_id: @board.id)
    @user = User.find(@board.user_id)
    @like = Like.new
  end

  def edit
    @board.attributes = flash[:board] if flash[:board]
  end

  def update
    if @board.update(board_params)
      redirect_to @board
    else
      redirect_back fallback_location: root_path , flash: {
        board: @board,
        error_messages: @board.errors.full_messages
      }
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, flash: { notice: "「#{@board.title}」の掲示板が削除されました" }
  end

  private

  def board_params
    params.require(:board).permit(:content, :image, :name, :title, :body, tag_ids: [])
  end

  def set_target_board
    @board = Board.find(params[:id])
  end
end

src/app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
    <% board.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
      <%# link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p><%= image_tag board.image, class: "width-max" if board.image.attached? %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
<% if @current_user == board.user %>
    <p><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></p>
<% else %>

<% end %>
    <br />
    <br />
      <% if board.user.image? %>
      <%= image_tag board.user.image.url, class:"img-thumbnail", style:" width: 100px; height: 100px; object-fit: cover; border-radius: 50%;" %>
      <% else %>
      <%= image_tag "noimage.png", class:"img-thumbnail", style:" width: 100px; height: 100px; object-fit: cover; border-radius: 50%;"; %>
      <% end %>
    <p>投稿者名　<%= @board.user.name %> </p>
    <p><%= link_to '投稿者のプロフィール', user_path(board.user_id), class: 'btn btn-outline-dark' %></p>
<p><i class="fa fa-heart" aria-hidden="true"></i>　いいね数: <%= @board.likes.count %></h3>
<% if @current_user %>
<% if @current_user.already_liked?(@board) %>
  <%= button_to 'いいねを取り消す', board_like_path(@board), method: :delete %>
<% else %>
  <%= button_to 'いいね', board_likes_path(@board) %>
<% end %>
<% else %>
<p>ログインするといいねできます。</p>
<% end %>
<p>いいねしたユーザー</p>

<% @board.liked_users.each do |user| %>
        <li><% if user.image? %>
      <%= image_tag user.image.url, class:"img-thumbnail", style:" width: 50px; height: 50px; object-fit: cover; border-radius: 50%;" %>
      <% else %>
      <%= image_tag "noimage.png", class:"img-thumbnail", style:" width: 50px; height: 50px; object-fit: cover; border-radius: 50%;"; %>
      <% end %>
<%= user.name %></li>
<% end %>
<br>
        <p class="card-text"><i class="fa fa-clock-o" aria-hidden="true"></i>　更新日　<%= board.updated_at.to_s(:datetime_jp) %></p>
    <p class="card-text"><i class="fa fa-clock-o" aria-hidden="true"></i>　公開日　<%= board.created_at.to_s(:datetime_jp) %></p>
    
  </div>
</div>

src/app/views/boards/_form.html.erb
<%= render 'shared/error_messages' %>
<%= form_with model: board do |f| %>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <span class="image">
  <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
    <div class="form-group">
    <span>タグ</span>
    <span>※一度につけられるタグは１つまでです。 </span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  $("#board_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#board_image").val("");
    }
  });
</script>

src/app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集　</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '掲示板一覧', boards_path, class:"btn btn-outline-dark" %>
  </div>
</div>
<%= render partial: 'form', locals: {board: @board} %>

src/app/views/boards/index.html.erb
 <!-- タブ切り替え -->
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a href="#photo1" class="nav-link  <% if params[:q].present? %>active<% end %>" data-bs-toggle="tab">タグで調べる</a>
        </li>
        <li class="nav-item">
          <a href="#photo2" class="nav-link  <% if params[:q].present? %>active<% end %>" data-bs-toggle="tab">キーワード検索</a>
        </li>
      </ul>

      <!-- 掲示板 -->
      <div class="tab-content">
        <div id="photo1" class="tab-pane active">
          <div class="d-lg-flex align-items-center">
  <h1>北星掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
      <%= form_with url: boards_path, method: :get, class: 'boards__searchForm' do %>
        <%= select_tag :tag_id, 
                      options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                      {
                        prompt: 'タグで絞り込み',
                        class: 'form-control boards__select',
                        onchange: 'submit(this.form);'
                      }
      %>
      <% end %>
    <% if @current_user %>
    <%= link_to '新しく投稿する', new_board_path, class:"btn btn-outline-dark" %>
    <% else %>
    <p>投稿機能はログインしてからできます。</p>
    <% end %>
  </div>
</div>
<p>北星掲示板では、大学生活についての悩みを書き込めます</p>
<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>
<ul>
<li>投稿数　全<%= @boards_count %>件</li>
</ul>
<%# <p>並び替え 古い順　新しい順　いいねが多い順　コメントが多い順</p> %>

<div class="row">
    <% @boards.each do |board| %>
      <div class="col-sm-6">
        <div class="card">
        <%= link_to board_path(board), style: "width:100%; height:100%; display:block;"  do %>
        <h5  class="card-title"><%= board.title %></h5>
        <br class="d-lg-none">
        <% board.tags.each do |tag| %>
        <li class="badge badge-primary"><%= tag.name %><br></li> 
        <% end %>
      <p class="card-text"><i class="fa fa-commenting-o" aria-hidden="true"></i>　<%= board.comments.count %>　<i class="fa fa-heart" aria-hidden="true"></i>　<%= board.likes.count %></p> 
     <p  class="card-text"> <% if board.user.image? %>
      <%= image_tag board.user.image.url, class:"img-thumbnail", style:" width: 50px; height: 50px; object-fit: cover; border-radius: 50%;"  %>
      <% else %>
      <%= image_tag "noimage.png", class:"img-thumbnail" , style:" width: 50px; height: 50px; object-fit: cover; border-radius: 50%;"%>
      <% end %>
      <%= board.user.name %>　<i class="fa fa-clock-o" aria-hidden="true"></i><%= board.created_at.to_s(:datetime_jp) %></p>
        <% end %>
    </div>
</div>
    <% end %>
</div>

<%= paginate @boards %>
                  </div>
        <div id="photo2" class="tab-pane">
        <div class="d-lg-flex align-items-center">
  <h1>北星掲示板一覧</h1>

  
  <div class="ml-auto boards__linkBox">
    <% if @current_user %>
    <%= link_to '新しく投稿する', new_board_path, class:"btn btn-outline-dark" %>
    <% else %>
    <p>投稿機能はログインしてからできます。</p>
    <% end %>
  </div>
    <%= search_form_for @q do |f| %>
        <%= f.search_field :title_cont %>
        <%= f.submit %>
    <% end %>
</div>
<p>北星掲示板では、大学生活についての悩みを書き込めます</p>
<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>
<ul>
<li>投稿数　全<%= @boards_count %>件</li>
</ul>
<%# <p>並び替え 古い順　新しい順　いいねが多い順　コメントが多い順</p> %>

<div class="row">
    <% @boards.each do |board| %>
      <div class="col-sm-6">
        <div class="card">
        <%= link_to board_path(board), style: "width:100%; height:100%; display:block;"  do %>
        <h5  class="card-title"><%= board.title %></h5>
        <br class="d-lg-none">
        <% board.tags.each do |tag| %>
        <li class="badge badge-primary"><%= tag.name %><br></li> 
        <% end %>
      <p class="card-text"><i class="fa fa-commenting-o" aria-hidden="true"></i>　<%= board.comments.count %>　<i class="fa fa-heart" aria-hidden="true"></i>　<%= board.likes.count %></p> 
     <p  class="card-text"> <% if board.user.image? %>
      <%= image_tag board.user.image.url, class:"img-thumbnail", style:" width: 50px; height: 50px; object-fit: cover; border-radius: 50%;"  %>
      <% else %>
      <%= image_tag "noimage.png", class:"img-thumbnail" , style:" width: 50px; height: 50px; object-fit: cover; border-radius: 50%;"%>
      <% end %>
      <%= board.user.name %>　<i class="fa fa-clock-o" aria-hidden="true"></i><%= board.created_at.to_s(:datetime_jp) %></p>
        <% end %>
    </div>
</div>
    <% end %>
</div>

<%= paginate @boards %>
        </div>
      </div>

src/app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>
<%= render @board %>

<% if @current_user %>
<div class="p-comment__list">
  <div class="p-comment__listTitle"><i class="fa fa-commenting-o" aria-hidden="true"></i>コメント　<%= @board.comments.count %>件</div>
  <%= render @board.comments %>
</div>
<%= render partial: 'comments/form', locals: { comment: @comment } %>
<% else %>
<div class="p-comment__list">
  <div class="p-comment__listTitle"><i class="fa fa-commenting-o" aria-hidden="true"></i>コメントはログインするとできるようになります。</div>
</div>
<% end %>