src/config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index' 
  resources :users
  get 'mypage', to: 'users#me'
  get 'user_edit', to: 'users#edit'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  
  # root 'home#index'
  # root 'boards#index'
  # , only: %i[new create edit update show]
  resources :boards do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: %i[create destroy]

  resources :contacts
  post 'contacts/confirm', to: 'contacts#confirm', as: 'contact_confirm'
  post 'contacts/index', to: 'contacts#index', as: 'contact_index'
  post 'contacts/done', to: 'contacts#done', as: 'contact_done'

  get "search" => "searches#search"
end

src/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  birthday        :date
#  faculty         :string(255)
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  profile         :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#
class User < ApplicationRecord
  has_secure_password
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_boards, through: :likes, source: :board
  #userがどの投稿をいいねしているのかを簡単に取得
  mount_uploader :image, ImageUploader

  def already_liked?(board)
    self.likes.exists?(board_id: board.id)
  end
  #すでにいいねをしているのかどうかを判定

  validates :name,
    presence: true,
    uniqueness: true,
    length: {maximum:16}
  validates :password,
    length: {minimum: 8 }
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save!
      session[:user_id] = user.id
      #セッションにuse.id入れる
      redirect_to mypage_path
    else
      flash[:user] = user
      flash[:error_messages] = user.errors.full_messages
      redirect_back fallback_location: 'http://localhost'
    end
  end

  def me
    #自分のプロフィールページ
  @user = @current_user
  end

  def show
  @user = User.find(params[:id])
  if @user == @current_user
    redirect_to :action => 'me'
    #もしusers詳細ページがcurrent_userならmeページにリダイレクトする
  else
  end
  end

  def edit
  @user = @current_user
  end

  def update
    user = @current_user
    if user.update(user_params)
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      flash[:error_messages] = user.errors.full_messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :faculty, :profile, :image)
  end
end

src/app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>
<%= form_with model: user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :faculty, '学部学科' %>
    <%= f.text_field :faculty, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード(8文字以上)' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

src/app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :image, 'プロフィール画像' %>
    <%= f.file_field :image, class: 'form-control'  %>
    <%= f.label :profile, 'プロフィール文章' %>
    <%= f.text_area  :profile, class: 'form-control', rows: 10  %>
    <%= f.label :password, 'パスワード(8文字以上)' %>
    <%= f.password_field :password, class: 'form-control' %>
    </div>
      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

src/app/views/users/me.html.erb
<h1>マイページ</h1>

<p>ここでは、プロフィールの設定や確認を行えます。</p>

<% if @current_user.image? %>
  <%= image_tag @current_user.image.url, style:" width: 200px; height: 200px; object-fit: cover; " %>
<% else %>
  <%= image_tag "noimage.png", style:" width: 200px; height: 200px; object-fit: cover; " %>
<% end %>

<p>名前　<%= @current_user.name %></p>
<p>学部学科　<%= @current_user.faculty %></p>
<p>プロフィール</p>
<p><%= @current_user.profile %></p>
<p><%= link_to 'プロフィール編集', user_edit_path, class:"btn btn-outline-dark" %></p>


<h5>いいねしている投稿　<%=  @current_user.liked_boards.count %>件</h5>

<br />
ーーーーーーーーーーーーーーー
<% @current_user.liked_boards.each do |board| %>
  <br />
  投稿タイトル：<%= board.title %>
  <br />
  投稿者名：<%= board.user.name %>
  <br />
  投稿本文：<%= board.body %>
  <br />
ーーーーーーーーーーーーーーー
<% end %>

src/app/views/users/show.html.erb
<h1>他のユーザー</h1>

<% if @user.image? %>
  <%= image_tag @user.image.url, style:" width: 200px; height: 200px; object-fit: cover";  %>
<% else %>
  <%= image_tag "noimage.png", style:" width: 200px; height: 200px; object-fit: cover";  %>
<% end %>
<br />
<br />
<br />
<p>名前　<%= @user.name %></p>
<p>学部学科　<%= @user.faculty %></p>
<p>プロフィール</p>
<p><%= @user.profile %></p>