src/config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index' 
  resources :users
  get 'mypage', to: 'users#me'
  get 'user_edit', to: 'users#edit'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  
  # root 'home#index'
  # root 'boards#index'
  # , only: %i[new create edit update show]
  resources :boards do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments, only: %i[create destroy]

  resources :contacts
  post 'contacts/confirm', to: 'contacts#confirm', as: 'contact_confirm'
  post 'contacts/index', to: 'contacts#index', as: 'contact_index'
  post 'contacts/done', to: 'contacts#done', as: 'contact_done'

  get "search" => "searches#search"
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #CSRF対策(Webサイトの脆弱性をつくようなサイバー攻撃)
  before_action :current_user

  def about
  end

  def contact
  end

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end
end

src/app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-link">
        <%= link_to 'ホーム', root_path  %>
      </li>
      <li class=" nav-link">
        <%= link_to '掲示板一覧', boards_path  %>
      </li>
      <li class=" nav-link">
        <%= link_to 'About', about_path  %>
      </li>
      <li class=" nav-link">
        <%= link_to 'お問い合わせ',  contact_index_path, method: :post  %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if @current_user %>
          <%= @current_user.name %> さん
        <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if @current_user %>
            <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
            <%= link_to 'ログイン', root_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
    <%# <form class="form-inline my-2 my-lg-0">
    </form> %>
  </div>
</nav>

src/app/views/application/about.html.erb
<h1>About</h1>

src/app/views/application/contact.html.erb
<h1>お問い合わせ</h1>